### ISSUE TITLE
How to add some rendering using jquery to tree?

### ISSUE THREAD

**Issue by BlackZork** [dump247/angular.tree#6]
Hi,

I have two level tree and want to add some click handlers and visual effects like slideToggle to second level to template. How to do it?

I created another directive with lower priority and tried to emit event from my controller (scope.$on and scope.$broadcast), after tree data is loaded, but this event is caught to early - before tree is rendered.

I need a way to know when tree is changed and attach a callback to add my events to added nodes.

Any help appreciated!

**Comment by dump247** [comment]
To produce a different template for second level nodes, you can use ng-switch to conditionally render different content based on the type of node or other condition.

Unfortunately, this is a classic angularjs problem. As far as I know, angular does not give you a way to know when the dom/template is rendered. The best method I have found is to use $timeout to push your changes after rendering is complete.

**Comment by BlackZork** [comment]
Finally I resolved it with directive that has click handler and traverse down into ul > li hierarchy. My tree has only two levels so this is not a problem in this case. Many thanks for your work!
